spring:
  datasource:
    url: jdbc:mysql://jenkins-db.cqtcoxtsih2h.us-east-1.rds.amazonaws.com:3306/hr
    password: Admin12345
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  main:
#    web-application-type: none
server:
  port: 5000

  
  